### ISSUE TITLE
More descriptive errors, please

### ISSUE THREAD

**Issue by anonymousandrew** [grow/pygrow#98]
When running my local instance of grow, I'll receive an error message that says:
The resource could not be found.
or
stream.js:94
      throw er; // Unhandled stream error in pipe.

I'm uncertain what to do with these. The first error doesn't tell me what I'm missing, and the second seems to be more of a warning than an error? I'm not sure what's causing it.

**Comment by jeremydw** [comment]
The second error message sounds like something Gulp is throwing up, so sadly we can't fix that. That said, the "The resource could not be found." we can definitely improve. The log message should should show the path from the request and the local file path that it tried to find.

**Comment by jeremydw** [comment]
Made a few really good improvements to error handling.

Firstly, in the console, we now show the timestamp and request path for 404s, rather than just the error message.

![image](https://cloud.githubusercontent.com/assets/646525/9153613/44e27ee6-3e17-11e5-819b-804827408db3.png)

Secondly, we've improved the error messages on the error page, with more specific debugging information. We also show the pod root at the footer of this page for folks that might be running multiple instances of the dev server.

![image](https://cloud.githubusercontent.com/assets/646525/9153614/58d3f4f2-3e17-11e5-895e-6a7c117b0137.png)
